global:
  scrape_interval: 15s
  # scrape_timeout: 50s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'example-job-1'
    static_configs:
      - targets: ['<target-1-ip>:9100']

  - job_name: 'example-job-2'
    static_configs:
      - targets: ['<target-2-ip>:9100']

  - job_name: 'example-job-3'
    static_configs:
      - targets: ['<target-3-ip>:9100']
